(define (calculate d m c y)
  (modulo (+ (-  (floor (- (* 2.6 m) 0.2) ) (* 2 c)) y d  (floor (/ y 4)) (floor (/ c 4))) 7))
(define (day-of-week d m y)
  (define (for_jan&feb d m y)
    (cond ((or (= m 1) (= m 2))
           (modulo (inexact->exact(calculate d (+ m 10) (quotient y 100) (modulo (- y 1 ) 100))) 7))
        ((not(or (= m 1) (= m 2)))
         (modulo (inexact->exact(calculate d (- m 2) (quotient y 100) (modulo y 100))) 7))))
  (for_jan&feb d m y))
